steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'africa-south1-docker.pkg.dev/automation-269209/audience-sync-repo/audience-sync-api:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'africa-south1-docker.pkg.dev/automation-269209/audience-sync-repo/audience-sync-api:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'audience-sync-api'
      - '--image=africa-south1-docker.pkg.dev/automation-269209/audience-sync-repo/audience-sync-api:$SHORT_SHA'
      - '--region=africa-south1'

images:
  - 'africa-south1-docker.pkg.dev/automation-269209/audience-sync-repo/audience-sync-api:$SHORT_SHA'