apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: audience-sync-api
spec:
  template:
    metadata:
      labels:
        service-type: "audience-sync-api"
      annotations:
        deployment-timestamp: "0"
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
        - image: africa-south1-docker.pkg.dev/automation-269209/audience-sync-repo/audience-sync-api
          ports:
            - containerPort: 8000
          env:
            - name: SYSTEM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: SYSTEM_TOKEN
                  key: 'latest'
            - name: META_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: META_ACCESS_TOKEN
                  key: 'latest'