"""add checkpoint message and audit meta fields

Revision ID: a823a1baad42
Revises: 202dbcac7a49
Create Date: 2026-08-04 13:35:37.235030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a823a1baad42'
down_revision: Union[str, Sequence[str], None] = '202dbcac7a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_invalid_entries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_invalid_samples', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('missing_email_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('checkpoint_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_logs', schema=None) as batch_op:
        batch_op.drop_column('message')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('missing_email_count')
        batch_op.drop_column('meta_invalid_samples')
        batch_op.drop_column('meta_invalid_entries')

    # ### end Alembic commands ###
