"""initial schema

Revision ID: 202dbcac7a49
Revises: 
Create Date: 2026-07-15 09:39:28.064544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202dbcac7a49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('audience_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'audience_name', 'platform', name='uq_account_audience_platform')
    )
    with op.batch_alter_table('approved_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approved_accounts_account'), ['account'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('audience_name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.JSON(), nullable=True),
    sa.Column('dispatched', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.JSON(), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=True)

    op.create_table('batch_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'batch_id', name='uq_account_batch')
    )
    with op.batch_alter_table('batch_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_registrations_account'), ['account'], unique=False)

    op.create_table('checkpoint_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoint_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoint_logs_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoint_logs_request_id'))

    op.drop_table('checkpoint_logs')
    with op.batch_alter_table('batch_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_registrations_account'))

    op.drop_table('batch_registrations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approved_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approved_accounts_account'))

    op.drop_table('approved_accounts')
    # ### end Alembic commands ###
